# Generated by Django 3.0.8 on 2020-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('price', models.PositiveIntegerField()),
                ('photo_url', models.CharField(blank=True, max_length=4096, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('expiration', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'item',
                'db_table': 'app_item',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, max_length=128, null=True)),
                ('order_id', models.BigIntegerField()),
                ('data', models.CharField(max_length=32768)),
            ],
            options={
                'verbose_name': 'notification',
                'db_table': 'app_notification',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'order',
                'db_table': 'app_order',
            },
        ),
    ]
